### PR TITLE
Removing nokogiri version restriction

### PR DESCRIPTION
**Pull request by blackcofla**
There is a security issue in nokogiri version 1.6.8.1

### CODE REVIEW

**Comment by cbales** [comment]
Hi blackcofla, unfortunately we must include a specific major and minor version of the packages we use, since they must be approved by our legal team. However, I will check that the latest version has been approved and update this

**Comment by schneidmaster** [comment]
@cbales Thanks for updating. Could you also publish a new version to rubygems when you get a chance?

**Comment by blackcofla** [comment]
Thanks @cbales, will wait for a new gem version, appreciate the quick response

**Comment by cbales** [comment]
[microsoft_graph-0.1.3.gem](https://rubygems.org/gems/microsoft_graph) is now available.
Thanks for helping us keep this package up-to-date!

**Comment by schneidmaster** [comment]
Thanks @cbales! Really appreciate the prompt release.

**Pull request closed without merging**
