### PR TITLE
Enable to support Nokogiri >= 1.10.3

### PR DESCRIPTION
**Pull request by JunichiIto**
For the issue https://github.com/microsoftgraph/msgraph-sdk-ruby/issues/44

### CODE REVIEW

**Comment by MIchaelMainer** [comment]
What's the benefit of requiring "adal/request_parameters"? Don't we get that when we require adal?

**Comment by JunichiIto** [comment]
@MIchaelMainer Without this, I get `uninitialized constant ADAL::ClientAssertionCertificate::RequestParameters` error when I run rspec.

This issue is related: https://github.com/AzureAD/azure-activedirectory-library-for-ruby/issues/44

As I mentioned in the comment, it will be fixed if the following PR is released, but it has been ignored for a long time.

https://github.com/AzureAD/azure-activedirectory-library-for-ruby/pull/50

**Comment by NDuggan** [comment]
@JunichiIto Hi, we've just tried to use this as well and the latest gem on Rubygems doesn't seem to be updated/have a release so I've had to link directly to the git commit ref. Could we get a new release please?

**Comment by JunichiIto** [comment]
@NDuggan Sorry, I am not the maintainer of this gem.

@MIchaelMainer This PR has been merged but it's not released. Could you release it please?

**Comment by NDuggan** [comment]
@JunichiIto apologies, I misread contributor. Thanks for the push in the right direction though!

**Pull request merged**
